# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'StartUpRating' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StartUpRating
  pod 'Apollo', '~> 0.9.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Cosmos', '~> 17.0'

  target 'StartUpRatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StartUpRatingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
